api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "send-gift-cards-segment"
uid = "eb35b3f2-9ff0-3f60-e589-532480d324758e1726c7"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/ActionExtension.tsx"
target = "admin.customer-segment-details.action.render"
