import { CREATE_JOB_RULES } from "../../../shared/create-job";

export const globalVarsCreateGiftCards = {
  countMaxVolume: CREATE_JOB_RULES.countMaxVolume,
  prefixMaxChars: CREATE_JOB_RULES.prefixMaxChars,
  postfixMaxChars: CREATE_JOB_RULES.postfixMaxChars,
  prefixRegex: CREATE_JOB_RULES.prefixRegex,
  postfixRegex: CREATE_JOB_RULES.postfixRegex,
  valueMax: CREATE_JOB_RULES.valueMax,
  valueRegex: /^(\d+)?(\.\d{0,2})?$/,
  noteMaxChars: CREATE_JOB_RULES.noteMaxChars,
  codeLngDefault: CREATE_JOB_RULES.codeLengthDefault,
  codeLngMin: CREATE_JOB_RULES.codeLengthMin,
  codeLngMax: CREATE_JOB_RULES.codeLengthMax,
  presetMaxChars: CREATE_JOB_RULES.presetMaxChars,
  scheduledMessageMaxChars: CREATE_JOB_RULES.scheduledMessageMaxChars,
  isTest: false,
};

export const globalVarsTooltips = {
  createGiftCardLength:
    "The length of the gift card code. Min " +
    globalVarsCreateGiftCards.codeLngMin +
    ", Max " +
    globalVarsCreateGiftCards.codeLngMax +
    ". Default: " +
    globalVarsCreateGiftCards.codeLngDefault +
    ".",
  createGiftCardPrefix:
    "Add a custom prefix to each autogenerated gift card. Alphahumerical (A-Z) (0-9) values only. Max 4 characters.",
  createGiftCardPostfix:
    "Add a custom postfix to each autogenerated gift card. Alphahumerical (A-Z) (0-9) values only. Max 4 characters.",
  createGiftCardExpire:
    "After this date, the gift card will be invalid. Empty for no expiration.",
  createGiftCardScheduledDate: "Send the gift card on a specific date.",
  createGiftCardScheduledTime: "Send the gift card at a specific time.",
  createGiftCardScheduledMessage: "Customer will receive this message in E-Mail",
  createGiftCardScheduledSendOut: "If you want to schedule the send out to a future date",
  createGiftCardScheduledTimezone: "Select the timezone of the customer's shop",
};
